[package]
name = "authk"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI tooks for authk"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
